name: Pull Request Update

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

jobs:
  build:
    uses: viam-modules/common-workflows/.github/workflows/lint_and_test.yaml@main
    with:
      test_script_name: scripts/test.sh
    secrets:
      VIAM_API_KEY_ID: ${{ secrets.VIAM_DEV_API_KEY_ID }}
      VIAM_API_KEY: ${{ secrets.VIAM_DEV_API_KEY }}
      VIAM_ORG_ID: ${{ secrets.VIAM_DEV_ORG_ID }}
      VIAM_DATASET_ID: ${{ secrets.VIAM_DEV_DATASET_ID }}
